# Generated by Django 6.0.7 on 2026-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_nickname', models.CharField(max_length=255, null=True)),
                ('employee_group', models.CharField(max_length=255, null=True)),
                ('employee_position', models.CharField(max_length=255, null=True)),
                ('employee_birthdate', models.DateField()),
                ('employee_hiredate', models.DateField()),
                ('employee_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('employee_sss', models.CharField(max_length=20, null=True)),
                ('employee_gsis', models.CharField(max_length=20, null=True)),
                ('employeeActive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['employee_name'],
            },
        ),
    ]
