# Generated by Django 6.0.7 on 2026-08-04 11:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='AreaPrice',
            fields=[
                ('area_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_prices.area')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
