# Generated by Django 6.0.7 on 2026-08-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_prices', '0001_initial'),
        ('products', '0003_product_discontinued'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area_price',
            new_name='AreaPrice',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=255),
        ),
    ]
