# Generated by Django 6.0.7 on 2026-08-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_business_name', models.CharField(default='', max_length=255)),
                ('customer_contact_person', models.CharField(default='', max_length=255)),
                ('customer_mobile_no', models.CharField(default='', max_length=15)),
                ('customer_business_address', models.CharField(default='', max_length=255)),
                ('customer_active', models.BooleanField(default=True)),
                ('customer_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_prices.area')),
            ],
            options={
                'ordering': ['customer_business_name'],
            },
        ),
    ]
