# Generated by Django 6.0.7 on 2026-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_customer_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_active',
            field=models.BooleanField(default=False),
        ),
    ]
