# Generated by Django 6.0.7 on 2026-08-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_prices', '0002_rename_area_price_areaprice_alter_area_area_name'),
        ('customers', '0003_alter_customer_customer_active'),
        ('employees', '0002_alter_employee_employeeactive_and_more'),
        ('products', '0003_product_discontinued'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('control_no', models.CharField(max_length=15, unique=True)),
                ('van_number', models.IntegerField(blank=True, null=True)),
                ('beg_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='employees.employee')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='area_prices.area')),
            ],
            options={
                'ordering': ['-beg_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('MLOAD', 'MLOAD'), ('MRET', 'MRET'), ('VBO', 'VBO')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('line_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lines', to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.orderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.IntegerField(unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='orders.orderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('SO', 'SO'), ('SAM', 'SAM'), ('CRET', 'CRET'), ('CBO', 'CBO')], max_length=10)),
                ('invoice_type', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHARGE', 'Charge'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('line_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.customerdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_lines', to='products.product')),
            ],
        ),
    ]
