# Generated by Django 6.0.7 on 2026-08-03 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_prices', '0002_rename_area_price_areaprice_alter_area_area_name'),
        ('customers', '0002_alter_customer_customer_business_address_and_more'),
        ('employees', '0002_alter_employee_employeeactive_and_more'),
        ('products', '0003_product_discontinued'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('od_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('od_control_no', models.CharField(max_length=15)),
                ('od_van_number', models.IntegerField(null=True)),
                ('od_beg_date', models.DateTimeField(auto_now_add=True)),
                ('od_end_date', models.DateTimeField(null=True)),
                ('od_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('od_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_prices.area')),
            ],
        ),
        migrations.CreateModel(
            name='Marketing_details',
            fields=[
                ('md_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('md_total_SO', models.IntegerField()),
                ('md_total_SAM', models.IntegerField()),
                ('md_total_CRET', models.IntegerField()),
                ('md_total_CBO', models.IntegerField()),
                ('md_total_MLOAD', models.IntegerField()),
                ('md_total_MRET', models.IntegerField()),
                ('md_total_VBO', models.IntegerField()),
                ('md_control_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_details')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_details',
            fields=[
                ('dd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dd_order_type', models.CharField(choices=[('MLOAD', 'MLOAD'), ('MRET', 'MRET'), ('VBO', 'VBO')], max_length=10)),
                ('dd_quantity', models.IntegerField()),
                ('dd_line_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dd_product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('dd_control_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_details')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('cd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cd_invoice_no', models.IntegerField()),
                ('cd_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('cd_control_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_details')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_details',
            fields=[
                ('td_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('td_order_type', models.CharField(choices=[('SO', 'SO'), ('SAM', 'SAM'), ('CRET', 'CRET'), ('CBO', 'CBO')], max_length=10)),
                ('td_quantity', models.IntegerField()),
                ('td_line_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('td_invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer_details')),
                ('td_product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
