# Generated by Django 6.0.7 on 2026-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='order_type',
            field=models.CharField(choices=[('MLOAD', 'MLOAD'), ('MRET', 'MRET (-)'), ('VBO', 'VBO (-)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='order_type',
            field=models.CharField(choices=[('SO', 'SO'), ('SAM', 'SAM'), ('CRET', 'CRET (-)'), ('CBO', 'CBO (-)')], max_length=10),
        ),
    ]
