# Generated by Django 6.0.7 on 2026-08-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_deliverydetail_order_type_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='mload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='mret_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MarketingDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_SO', models.IntegerField(default=0)),
                ('total_SAM', models.IntegerField(default=0)),
                ('total_CBO', models.IntegerField(default=0)),
                ('total_CRET', models.IntegerField(default=0)),
                ('total_MLOAD', models.IntegerField(default=0)),
                ('total_MRET', models.IntegerField(default=0)),
                ('total_VBO', models.IntegerField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='orders.orderdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
