# Generated by Django 6.0.7 on 2026-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdetails_mload_date_orderdetails_mret_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
