# Generated by Django 6.0.7 on 2026-08-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderdetails_beg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='orders.orderdetails'),
        ),
    ]
