# Generated by Django 6.0.7 on 2026-08-05 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_marketingdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(default=datetime.datetime(2026, 8, 5, 16, 13, 32, 116870, tzinfo=datetime.timezone.utc)),
        ),
    ]
