# Generated by Django 6.0.7 on 2026-08-05 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderdetails_beg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
