# Generated by Django 6.0.7 on 2026-08-06 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderdetails_beg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
