# Generated by Django 6.0.7 on 2026-08-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderdetails_beg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(),
        ),
    ]
