# Generated by Django 6.1 on 2026-08-09 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderdetails_beg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='van_number',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
