# Generated by Django 6.1 on 2026-08-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderdetails_van_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetail',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='remarks',
        ),
    ]
