# Generated by Django 6.0.7 on 2026-08-13 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_prices', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('orders', '0013_remove_deliverydetail_remarks_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_details', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='orders.orderdetails'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.orderdetails'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketingdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing', to='orders.orderdetails'),
        ),
        migrations.AlterField(
            model_name='marketingdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='area_prices.area'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='customer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.customerdetails'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='products.product'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
