# Generated by Django 6.1 on 2026-08-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderdetails_created_at_orderdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='invoice_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
