# Generated by Django 6.1 on 2026-08-18 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_customerdetails_invoice_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='orders.orderdetails'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.orderdetails'),
        ),
        migrations.AlterField(
            model_name='marketingdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='orders.orderdetails'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='customer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.customerdetails'),
        ),
    ]
