# Generated by Django 6.1 on 2026-08-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_customerdetails_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='beg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
