# Generated by Django 6.0.7 on 2026-08-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('factory_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shelf_life', models.CharField(max_length=255)),
                ('product_packaging', models.CharField(max_length=255)),
                ('discontinued', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
