# Generated by Django 6.0.7 on 2026-08-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(default='', max_length=255)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('factory_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shelf_life', models.CharField(default='', max_length=255)),
                ('product_packaging', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
