# Generated by Django 6.0.7 on 2026-08-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='factory_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_packaging',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(max_length=255),
        ),
    ]
